### ISSUE TITLE
rn构建跑不起来

### ISSUE THREAD

**Issue by LWenH** [fmtjava/ReactNative_Eyepetizer#3]
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at NodeWatcher.checkedEmitError (/Users/wen/Downloads/ReactNative_Eyepetizer-main/node_modules/_sane@4.1.0@sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:203:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}

**Comment by fmtjava** [comment]
试一下：
brew update
brew install watchman
